### ISSUE TITLE
Help documentation is not working for error log view

### ISSUE THREAD

**Issue by SivaMaplelabs** [vmware/hillview#408]
Steps to reproduce
1. Generate some error(io.grpc.StatusRuntimeException: CANCELLED: Failed to read message.
)
2. Click on the help documentation icon in the view

**Comment by SivaMaplelabs** [comment]
![hillview-1](https://user-images.githubusercontent.com/22631594/45540852-1f1e8b00-b82b-11e8-9db2-6ea9f6e72c5a.PNG)

**Comment by mbudiu-vmw** [comment]
In general the help does not apply to errors, but the specific kind of views. In this case no view was generated because the data could not be loaded at all.
We should perhaps add help for specific errors too.
That being said, this was a real bug, because the links in the web pages should point back at the user manual, and all the links were broken; the links will now be correctly generated and checked by a script.
