### ISSUE TITLE
Error: invalid option: -y

### ISSUE THREAD

**Issue by edoliberty** [vmware/hillview#516]
When running 
./install-dependencies.sh
I get
Error: invalid option: -y
(which is true, it really doesn't exist...)

**Comment by SivaMaplelabs** [comment]
While installing curl, it is required to pass an affirmative answer (https://github.com/vmware/hillview/blob/master/bin/install-dependencies.sh#L15)

**Comment by SivaMaplelabs** [comment]
siva:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

siva:~$ apt-get install curl
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
sdpteam@jarvis-auto-001:~$ sudo su
root@jarvis-auto-001:/apps/sdp# apt-get install curl
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  grub-pc-bin
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  libcurl4
The following packages will be upgraded:
  curl libcurl4
2 upgraded, 0 newly installed, 0 to remove and 168 not upgraded.
Need to get 373 kB of archives.
After this operation, 0 B of additional disk space will be used.
**Do you want to continue? [Y/n]** ------------------------------------------->>>

**Comment by SivaMaplelabs** [comment]
siva# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.5 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"

siva# yum install curl
Loaded plugins: fastestmirror, langpacks, merge-conf, priorities, product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Determining fastest mirrors
redhat_updates                                                                                                                                                                      13594/13594
852 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package curl.x86_64 0:7.29.0-46.el7 will be updated
---> Package curl.x86_64 0:7.29.0-51.el7 will be an update
--> Processing Dependency: libcurl = 7.29.0-51.el7 for package: curl-7.29.0-51.el7.x86_64
--> Running transaction check
---> Package libcurl.x86_64 0:7.29.0-46.el7 will be updated
---> Package libcurl.x86_64 0:7.29.0-51.el7 will be an update
--> Processing Dependency: nss-pem(x86-64) >= 1.0.3-5 for package: libcurl-7.29.0-51.el7.x86_64
--> Running transaction check
---> Package nss-pem.x86_64 0:1.0.3-4.el7 will be updated
---> Package nss-pem.x86_64 0:1.0.3-5.el7_6.1 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================================================================================================================================
 Package                                   Arch                                     Version                                              Repository                                        Size
================================================================================================================================================================================================
Updating:
 curl                                      x86_64                                   7.29.0-51.el7                                        redhat_updates                                   269 k
Updating for dependencies:
 libcurl                                   x86_64                                   7.29.0-51.el7                                        redhat_updates                                   221 k
 nss-pem                                   x86_64                                   1.0.3-5.el7_6.1                                      redhat_updates                                    74 k

Transaction Summary
================================================================================================================================================================================================
Upgrade  1 Package (+2 Dependent packages)

Total download size: 564 k
**Is this ok [y/d/N]:**   ------------------------------------------------------------->>>

**Comment by SivaMaplelabs** [comment]
@edoliberty Could you through some light on this issue with the control flow of the script?
On which operating system, you have encountered this issue?

**Comment by mbudiu-vmw** [comment]
This must be for MacOS.

**Comment by mbudiu-vmw** [comment]
@edoliberty : I hope that this fixes the issue, but if not please reopen it and provide us some details about your environment.

**Comment by edoliberty** [comment]
It actually doesn't. Running on macos 10.14.4.
I'll try to fix and post a solution instead of a bug.

**Comment by edoliberty** [comment]
Here is what worked for me

1) Remove "-y" from line 15

${SUDO} ${INSTALL} install curl -y


"-y" is not a valid flag for homebrew.

2) I removed "libgfortran3" from line 24.

#${SUDO} ${INSTALL} install maven ${NODEJS} ${NPM} libgfortran3 unzip gzip


There does not appear to be a brew package for libgfortran3


edoliberty$ brew update

Already up-to-date.


edoliberty$ brew install libgfortran3

Error: No available formula with the name "libgfortran3"

==> *Searching for a previously deleted formula (in the last month)...*

Error: No previously deleted formula found.

==> *Searching for similarly named formulae...*

Error: No similarly named formulae found.

==> *Searching taps...*

==> *Searching taps on GitHub...*

Error: No formulae found in taps.



libgfortran3 is standard in fortran deployments which should be a part of
my gcc install asaik.

So, not yet sure if this fixes it or only punts on this problem for a later
stage...



3) Add brew install for "wget" which is not preloaded with macos default
(at least not for me)


4) General question, it's kind of a faux pas to use sudo with brew. Is that
avoidable?

**Comment by mbudiu-vmw** [comment]
I apologize, I don't have a Mac, so I am not testing on this system too frequently.
1) The last commit I did moved the curl installation to happen only for Linux
2) libgfortran is only used when doing PCA; if you don't do PCA, you don't need it. We should probably tweak the build system to remove that menu item if we could not locate libgfortran. We could also install it just for Linux.
3) I will add a wget installation using brew for MacOS.
4) ${SUDO} is just a variable, which we can set to empty for MacOS if everything works find without root. I would like that very much.
